### ISSUE TITLE
TAXII to MISP push fails with Unauthorized error message 

### ISSUE THREAD

**Issue by UOITGeorge** [MISP/MISP-Taxii-Server#30] opened 2017-11-24 20:25 UTC
Hello ,
I'm trying to push Taxii messages to MISP , when running run-taxii-poll.py i'm getting the unauthorized error message 
Server log is attached. 
Poll.log shows the following : 

INFO:__main__:Connecting to local server...
CRITICAL:__main__:Could not connect to local server
CRITICAL:__main__:UNAUTHORIZED:
[server.log](https://github.com/MISP/MISP-Taxii-Server/files/1502489/server.log)

I think the failing part is connection to Taxii but i can't find where to define the credentials 

Any advise ?

**Comment by FloatingGhost** [comment] 2017-11-25 21:57
>UNAUTHORIZED

OH GEEZE I WONDER WHAT THE ISSUE IS

It tells you where the files are in the readme you dolt.

![image](https://user-images.githubusercontent.com/4086403/33235222-0049763a-d277-11e7-871c-1e88af5ce706.png)

Closing as PEBKAC

**Closed by FloatingGhost** 2017-11-25 21:57 UTC
