### ISSUE TITLE
Connection Timed Out When Running Poll on Remote Server :(

### ISSUE THREAD

**Issue by obsidianpentesting** [MISP/MISP-Taxii-Server#13] opened 2017-06-20 19:03 UTC
I'm coming across a "[Errno 110] Connection timed out" error when running the following command against a remote server:

` /var/git/MISP-Taxii-Server/scripts$ sudo python3 run-taxii-poll.py `

I verified that I am able to successfully connect to the remote server and retrieve data using the following command:

`/var/git/MISP-Taxii-Server/scripts$ sudo taxii-poll --path https://MY.REMOTE.SERVER/taxii-discovery-service --cert /etc/ssl/private/MYCERT.crt --username MYUSERNAME --password MYPASSWORD--key /etc/ssl/private/MYSECURITYKEY.key --key-password MYKEYPASSWORD --verify no -c system.Default`

The 'taxi-push' test command also worked. I was able to see the sample STIX event appear my MISP instance's event list.

After spending a few days (hopelessly) tinkering, I cannot get past the timeout error. I tried adding date-time values in run-taxii-poll.py to create a shortened poll request (didn't work) and a few other things I am too embarrassed to mention (invoking the dark arts, anyone?). Please let me know if there is a fix.

Here is the complete traceback:

```
/var/git/MISP-Taxii-Server/scripts$ sudo python3 run-taxii-poll.py 
'cm9vdDpyb290' 12
127.0.0.1 - - [20/Jun/2017 13:42:51] "POST /services/discovery HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run-taxii-poll.py", line 86, in <module>
    for content_block in cli.poll(collection):
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/client11.py", line 485, in poll
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/abstract.py", line 167, in _execute_request
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/abstract.py", line 210, in _get_service
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/abstract.py", line 259, in get_services
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/abstract.py", line 304, in discover_services
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/client11.py", line 27, in _discovery_request
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/abstract.py", line 195, in _execute_request
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 58, in send_taxii_request
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 408, in get_response_using_key_pass
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by FloatingGhost** [comment] 2017-06-21 13:20
Hm, weird - can you post a redacted version of `~/.misptaxii/remote-servers.yml"?

Just wanna make sure nothing funny is going on in there

**Comment by obsidianpentesting** [comment] 2017-06-21 13:52
Sure thing...

```
- name: 'NICKNAME'
  host: MY.REMOTE.SERVER
  port: 9000
  discovery_path: /taxii-discovery-service
  use_https: True
  taxii_version: '1.1'
  headers:
  auth:
    username: MYUSERNAME
    password: MYPASSWORD
    cacert_path:
    jwt_auth_url:
    cert_file: /etc/ssl/private/MYCERT.crt
    key_file: /etc/ssl/private/MYKEY.key
    key_password: MYKEYPASSWORD
    verify_ssl: False
  collections:
    - system.Default
```

**Comment by FloatingGhost** [comment] 2017-06-21 14:19
```
- name: 'LOCAL'
  host: 127.0.0.1
  port: 9000
  discovery_path: /services/discovery
  use_https: False
  taxii_version: '1.1'
  headers:
  auth:
    username: root
    password: root
    cacert_path:
    jwt_auth_url:
    cert_file: 
    key_file: 
    key_password:  
  verify_ssl: False
  collections:
    - collection
- name: 'HailATaxii'
  host: hailataxii.com
  port: 80
  discovery_path: /taxii-discovery-service 
  use_https: False
  taxii_version: '1.1'
  headers:
  auth:
    username: guest
    password: guest
    cacert_path:
    cert_file:
    key_file:
    key_password:
    jwt_auth_url:
    verify_ssl: True
  collections:
    - guest.phishtank_com
```

I'm running with this config for testing and it seems to work 100% fine. 

`system.Default` suggests soltra, right? We don't have a licence for that, so I can't test it, but are you sure you've

1. Got the right port open on the server you're polling
2. Are actually accessing the right port - when I was testing this, I tried to hit hailataxii on 9000, which didn't work! 
3. Have IP whitelist if you use that

**Comment by obsidianpentesting** [comment] 2017-06-21 14:41
You're right, it's for FS-ISAC. Looks like changing the port to 443 did something...so far I'm still getting a bunch of output to the screen. It might be pulling *every* event from the repository. I'll let you know if this works out. This is what I'm getting back so far:

```
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:15] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:16] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:16] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:16] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:16] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
127.0.0.1 - - [21/Jun/2017 09:40:16] "POST /services/inbox HTTP/1.1" 200 -
'cm9vdDpyb290' 12
```
And so on, and so on...

**Comment by FloatingGhost** [comment] 2017-06-21 14:42
Yeah that's working as intended!

Taxii servers sync to eachother, so it'll cache everything to your database - it'll take much less time next time around!

**Comment by obsidianpentesting** [comment] 2017-06-21 14:43
THANK YOU!!!!! It looks like it hasn't pushed anything to MISP yet, but hopefully that works too ;]

**Comment by FloatingGhost** [comment] 2017-06-21 14:44
If you look at your local TAXII server log (the one you ran with opentaxii-run-dev), you'll see if it's managing to do stuff or if it's erroring out

**Comment by FloatingGhost** [comment] 2017-06-21 14:44
If it's not pushing anything, you likely ran it *without* exporting OPENTAXII_CONFIG

**Comment by obsidianpentesting** [comment] 2017-06-21 14:46
Awesome....I'm working on a remote server ATM, so I don't want to interrupt or put this into background just yet. I'll wait until this gets done and see what happens.

**Comment by obsidianpentesting** [comment] 2017-06-21 14:50
Ok, it apparently came across a problem...not sure what this is:

```
Traceback (most recent call last):
  File "run-taxii-poll.py", line 86, in <module>
    for content_block in cli.poll(collection):
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/client11.py", line 487, in poll
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 219, in _parse_response
  File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 118, in _stream_poll_response
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:148588)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:148286)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/lxml.etree.c:148925)
  File "src/lxml/parser.pxi", line 1339, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:113649)
  File "src/lxml/parser.pxi", line 586, in lxml.etree._ParserContext._handleParseResult (src/lxml/lxml.etree.c:104990)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "https://analysis.fsisac.com/taxii-data", line 211526
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 211526, column 2
```

**Comment by FloatingGhost** [comment] 2017-06-21 14:52
Oooh, bizarre. 

Sounds like a corrupted or otherwise invalid (as per python-stix) block

I'll try-catch the whole thing to stop that from happening

**Comment by FloatingGhost** [comment] 2017-06-21 15:02
Ok, try a git pull and try again

It'll log to a file this time, poll.log

and theoretically in the case that it fails to poll for any reason, it should move on cleanly.

**Comment by obsidianpentesting** [comment] 2017-06-21 15:12
Running well so far....;]

**Comment by obsidianpentesting** [comment] 2017-06-21 15:35
ahhh, it looks like it finished, but nothing shows up in MISP. I'll try exporting OPENTAXII_CONFIG again to be sure this isn't the problem.

Here's the output from poll.log:

```
> INFO:main:Connecting to local server...
> INFO:main:Connected
> INFO:main:== FS-ISAC ==
> INFO:cabby.client11.Client11:3 services discovered
> ERROR:main:FAILED TO POLL system.Default
> ERROR:main:StartTag: invalid element name, line 211526, column 2 (taxii-data, line 211526)
> Traceback (most recent call last):
> File "run-taxii-poll.py", line 103, in <module>
> for content_block in cli.poll(collection_name=collection):
> File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/client11.py", line 487, in poll
> for obj in stream:
> File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 219, in _parse_response
> for obj in _stream_poll_response(namespace, gen):
> File "/usr/local/lib/python3.5/dist-packages/cabby-0.1.17-py3.5.egg/cabby/dispatcher.py", line 118, in _stream_poll_response
> for action, elem in stream:
> File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.next (src/lxml/lxml.etree.c:148588)
> File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.next (src/lxml/lxml.etree.c:148286)
> File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/lxml.etree.c:148925)
> File "src/lxml/parser.pxi", line 1339, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:113649)
> File "src/lxml/parser.pxi", line 586, in lxml.etree._ParserContext._handleParseResult (src/lxml/lxml.etree.c:104990)
> File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
> File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
> File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
> File "https://analysis.fsisac.com/taxii-data", line 211526
> lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 211526, column 2
> INFO:main:Finished!
```

**Comment by FloatingGhost** [comment] 2017-06-21 15:50
As per gitter, it seems to be working~

So that's nice

Closing

**Closed by FloatingGhost** 2017-06-21 15:50 UTC
