### ISSUE TITLE
TAXII_PUSH ERROR: UNAUTHORIZED: 

### ISSUE THREAD

**Issue by trismegistusX** [MISP/MISP-Taxii-Server#27] opened 2017-11-06 22:02 UTC
Received the following error when pushing sample stix file to MISP:
Pushed file:
taxii-push --path http://localhost:9000/services/inbox -f /home/user/MISP-Taxii-Server/tests/sample.xml -v  --dest collection --user user --password password

Alert when file pushed to opentaxii-run-dev:
UnauthorizedException: UNAUTHORIZED, level=warning, timestamp=2017-11-06, logger=opentaxii.middleware, event=Status exception}
127.0.0.1 - - [06/Nov/2017 ] "POST /services/inbox HTTP/1.1" 200 -

`
2017-11-06  requests.packages.urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
2017-11-06  requests.packages.urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 200 306
2017-11-06  cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="7149768213953236338" in_response_to="0" status_type="UNAUTHORIZED"/>

2017-11-06 cabby.cli.commons ERROR: UNAUTHORIZED: 
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "build/bdist.linux-x86_64/egg/cabby/cli/push.py", line 51, in _runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "build/bdist.linux-x86_64/egg/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "build/bdist.linux-x86_64/egg/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "build/bdist.linux-x86_64/egg/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
UnsuccessfulStatusError: UNAUTHORIZED:
`
Added taxii auth user to config.yaml:
---
domain: "localhost:9000"
support_basic_auth: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://user:password@localhost/taxiipersist
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://user:password@localhost/taxiiauth
    create_tables: yes
    secret: SupersecretstringforOpenTaxiiserverinsertedhere

logging:
  opentaxii: info
  root: info

hooks: misp_taxii_hooks.hooks
# Sample configuration for misp_taxii_server

zmq:
    host: localhost
    port: 50000

misp:
    url: "https://xx.xx.xx.xx"
    api: apikey
    verifySSL: False

taxii:
    auth:
        username: user
        password: password
    collections:
        - collection

`
Added another taxii user and updated config.yaml and same "Unauthorized" error.
(Used same credentials for taxii auth as in taxiiauthDB and taxiipersistDB)

Config env:
OPENTAXII_CONFIG=/home/user/MISP-Taxii-Server/config/config.yaml

Adding new taxii auth accounts and update config.yaml file to test fails, what is the next step?
(Username and password checked each time)

**Comment by FloatingGhost** [comment] 2017-11-07 01:15
your username and/or password is incorrect.

Re-create your user, and make sure you actually have OPENTAXII_CONFIG exported when you run `opentaxii-create-account` which you should have been doing anyway.

Working as intended.

Closing.

**Closed by FloatingGhost** 2017-11-07 01:15 UTC

**Comment by trismegistusX** [comment] 2017-11-07 22:50
Removed previous setup (Databases + yaml files + taxii auth user)
Restarted from scratch again to install all components.

Worked then:
`
2017-11-07  requests.packages.urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
2017-11-07  requests.packages.urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 200 335
2017-11-07  cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="165722865095819851" in_response_to="bc7ee0fd-8736-4e09-927d-dc58b5502225" status_type="SUCCESS"/>

2017-11-07 cabby.client11.Client11 DEBUG: Content block successfully pushed
2017-11-07 cabby.cli.push INFO: Content block successfully pushed
`
Worth mentioning that export OPENTAXII_CONFIG is only remembered for that session and so needs to be added to /etc/environment permanently.
