### ISSUE TITLE
SQL Operational Error

### ISSUE THREAD

**Issue by arcsector** [MISP/MISP-Taxii-Server#17] opened 2017-09-26 22:31 UTC
I've completed the steps up to running `opentaxii-create-services -c config/services.yaml`. Now I'm trying to run and here is the error:

```
2017-09-26T22:25:53.594891Z [opentaxii.utils] info: api.initialized {timestamp=2017-09-26T22:25:53.594891Z, logger=opentaxii.utils, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 9, in <module>
    load_entry_point('opentaxii==0.1.10a1', 'console_scripts', 'opentaxii-create-services')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii-0.1.10a1-py2.7.egg/opentaxii/cli/__init__.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii-0.1.10a1-py2.7.egg/opentaxii/server.py", line 41, in __init__
    api=initialize_api(config['auth_api']))
  File "/usr/local/lib/python2.7/dist-packages/opentaxii-0.1.10a1-py2.7.egg/opentaxii/utils.py", line 36, in initialize_api
    instance = cls(**params)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii-0.1.10a1-py2.7.egg/opentaxii/auth/sqldb/api.py", line 41, in __init__
    self.db.create_all_tables()
  File "/usr/local/lib/python2.7/dist-packages/opentaxii-0.1.10a1-py2.7.egg/opentaxii/sqldb_helper.py", line 60, in create_all_tables
    self.metadata.create_all(bind=self.engine)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 3981, in create_all
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1929, in _run_visitor
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1538, in _run_visitor
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 791, in visit_table
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 945, in execute
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 504, in do_execute
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: u'\nCREATE TABLE accounts (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tusername VARCHAR(256), \n\tpassword_hash VARCHAR(256), \n\tPRIMARY KEY (id), \n\tUNIQUE (username)\n)\n\n']
```

Does this have to do with error handling or does it have to do with my MYSQL settings?

**Comment by FloatingGhost** [comment] 2017-09-27 08:32
I do not support python 2.7.

I explicitly state in the install instructions to use python 3. 

Please upgrade to a sane version and try again.

**Comment by FloatingGhost** [comment] 2017-09-27 08:35
Also this appears to be a dupe of #3

**Closed** 2017-10-19 17:30 UTC
Labels: I swear to god if I see "python2.7" in your stacktrace again
